require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

# temporary
Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CaseEquality:
  Enabled: false

# temporary
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Rails/UniqueValidationWithoutIndex:
  Enabled: false

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/**/*
    - test/**/*
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/environments/*
